name: Build SmartLife

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '*'

      - name: Restore dependencies
        run: dotnet restore SmartLife.sln

      - name: Build solution
        run: dotnet build SmartLife.sln --configuration Release

      - name: Publish executable
        run: dotnet publish SmartLife.sln --configuration Release --framework net8.0-windows10.0.19041 --output ./output

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: SmartLife-executable
          path: ./output
